# Generated by Django 4.2.7 on 2023-12-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_image_blog_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imageURL',
            new_name='image_URL',
        ),
    ]
