# Generated by Django 4.2.7 on 2023-12-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_imageurl_blog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_URL',
        ),
    ]
