# Generated by Django 4.2.7 on 2023-11-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0002_rename_name_product_title_remove_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='cart_user',
        ),
    ]
